site_name: yishang's notebook

theme: 
    name: material
# 代码块配置_1
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tracking # 在url中使用标题定位锚点
        - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
        - navigation.tabs.sticky # 滚动是隐藏顶部nav，需要配合navigation.tabs使用
#        - navigation.sections # nav节点缩进
#        - navigation.expand # 不折叠左侧nav节点
        - navigation.indexes # 指定节点index pages ，跟instant不兼容
        - navigation.path
        - toc.integrate # 右侧生产目录
        - navigation.top # 一键回顶部  
        - search.suggest
        - search.highlight
        - search.share

    logo: assets/icon/image.svg
plugins:
  - search

markdown_extensions:
# 图片
    - attr_list
    - md_in_html
# 图标  fontawesome https://fontawesome.com/icons?d=gallery&m=free   material design  https://materialdesignicons.com/ 
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
            custom_icons:
                - theme/my_icons
# 显示术语提示
    - abbr
    - pymdownx.snippets

# 提示警告栏  note abstract info tip success question warning failue danger bug example quote
    - admonition
    - pymdownx.superfences
    - pymdownx.details

# 代码块配置_2
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
#内容标签栏
    - pymdownx.superfences 
    - pymdownx.tabbed:
        alternate_style: true

# 表格
    - tables

# 格式化处理  删除线 下划线 注释 高亮
    - pymdownx.critic
    - pymdownx.caret 
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

# 列表  无序列表  有序列表  定义列表 任务列表
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true


nav:
    - 主页: index.md
    - 女娲补天:
        - 前言: backend/mends_the_sky.md 
        - 补基础:
            - 基础 : backend/basic/basic.md
            - 红黑树 : backend/basic/red_black_tree.md
    - 课程: 
        - 编程语言 : 
            - OverView : course/programming_languages/index.md
            - Emacs : course/programming_languages/emacs.md
        - rust:
            - OverView : course/rust/index.md
            - CheatSheet : course/rust/rust_cheat_sheet.md
    - 资料:
        - 非github资料 :
                - effictive_rust: useful_resource/readeable.md
    - about: about.md